# Generated by Django 3.2 on 2024-11-15 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basquetbol', '0003_entrenador_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='redes_sociales',
        ),
        migrations.AlterField(
            model_name='entrenador',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='color_principal',
            field=models.CharField(help_text='Color principal en formato hexadecimal', max_length=7),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='color_secundario',
            field=models.CharField(help_text='Color secundario en formato hexadecimal', max_length=7),
        ),
    ]
