# Generated by Django 5.1.1 on 2024-11-15 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basquetbol', '0003_entrenador_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='redes_sociales',
        ),
        migrations.AlterField(
            model_name='entrenador',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='color_principal',
            field=models.CharField(help_text='Color principal en formato hexadecimal', max_length=7),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='color_secundario',
            field=models.CharField(help_text='Color secundario en formato hexadecimal', max_length=7),
        ),
    ]
