# Generated by Django 5.1.1 on 2024-11-16 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basquetbol', '0004_remove_equipo_redes_sociales_alter_entrenador_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('fase', models.CharField(choices=[('Clasificatorias', 'Clasificatorias'), ('Cuartos', 'Cuartos'), ('Semifinal', 'Semifinal'), ('Final', 'Final')], max_length=50)),
                ('goles_local', models.PositiveIntegerField(blank=True, null=True)),
                ('goles_visitante', models.PositiveIntegerField(blank=True, null=True)),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_local', to='basquetbol.equipo')),
                ('equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_visitante', to='basquetbol.equipo')),
                ('estadio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basquetbol.estadio')),
            ],
        ),
    ]
