# Generated by Django 5.1.1 on 2024-11-16 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basquetbol', '0007_remove_partido_campeonato'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='campeonato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='basquetbol.campeonato'),
        ),
    ]
