# Generated by Django 5.1.1 on 2024-11-16 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basquetbol', '0008_partido_campeonato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='campeonato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basquetbol.campeonato'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='color_principal',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='color_secundario',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='logo',
            field=models.ImageField(blank=True, default='logos_equipos/default_logo.png', null=True, upload_to='logos_equipos/'),
        ),
    ]
