# Generated by Django 5.1.1 on 2024-11-16 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basquetbol', '0010_campeonato_equipos_alter_partido_campeonato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campeonato',
            name='equipos',
        ),
    ]
