# Generated by Django 5.1.1 on 2024-11-16 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basquetbol', '0011_remove_campeonato_equipos'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartidoEstadistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pases_equipo_local', models.PositiveIntegerField(default=0)),
                ('pases_equipo_visitante', models.PositiveIntegerField(default=0)),
                ('faltas_equipo_local', models.PositiveIntegerField(default=0)),
                ('faltas_equipo_visitante', models.PositiveIntegerField(default=0)),
                ('triples_equipo_local', models.PositiveIntegerField(default=0)),
                ('triples_equipo_visitante', models.PositiveIntegerField(default=0)),
                ('rebotes_equipo_local', models.PositiveIntegerField(default=0)),
                ('rebotes_equipo_visitante', models.PositiveIntegerField(default=0)),
                ('partido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to='basquetbol.partido')),
            ],
        ),
    ]
