# Generated by Django 5.1.1 on 2024-11-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basquetbol', '0012_partidoestadistica'),
    ]

    operations = [
        migrations.AddField(
            model_name='partidoestadistica',
            name='puntos_equipo_local',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partidoestadistica',
            name='puntos_equipo_visitante',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
