# Generated by Django 5.1.1 on 2024-11-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basquetbol', '0013_partidoestadistica_puntos_equipo_local_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campeonato',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='partido',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
