# Generated by Django 5.1.1 on 2024-11-16 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basquetbol', '0016_posicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='posicion',
            name='campeonato',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='basquetbol.campeonato'),
        ),
        migrations.AlterField(
            model_name='posicion',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basquetbol.equipo'),
        ),
    ]
