# Generated by Django 5.1.1 on 2024-11-18 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basquetbol', '0017_posicion_campeonato_alter_posicion_equipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='campeonato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='basquetbol.campeonato'),
        ),
    ]
