# Generated by Django 5.1.1 on 2024-11-18 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basquetbol', '0018_alter_equipo_campeonato'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrenador',
            old_name='nombre',
            new_name='nombre_entrenador',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='nombre',
            new_name='nombre_equipo',
        ),
    ]
