# Generated by Django 5.1.1 on 2024-11-18 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basquetbol', '0019_rename_nombre_entrenador_nombre_entrenador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posicion',
            name='campeonato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basquetbol.campeonato'),
        ),
        migrations.AlterField(
            model_name='posicion',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posiciones', to='basquetbol.equipo'),
        ),
    ]
