# Generated by Django 5.1.1 on 2024-11-20 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basquetbol', '0020_alter_posicion_campeonato_alter_posicion_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
