# Generated by Django 5.1.1 on 2024-11-20 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basquetbol', '0022_equipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrenador',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
