# Generated by Django 5.1.1 on 2024-11-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basquetbol', '0023_alter_entrenador_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='posicion',
            field=models.CharField(choices=[('BASE', 'Base'), ('ESCOLTA', 'Escolta'), ('ALERO', 'Alero'), ('ALA-PIVOT', 'Ala-Pívot'), ('PIVOT', 'Pívot')], default='BASE', max_length=20),
        ),
    ]
