# Generated by Django 5.1.1 on 2024-11-20 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basquetbol', '0024_alter_jugador_posicion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='fundacion',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='usuario',
        ),
    ]
