# Generated by Django 5.1.1 on 2024-11-20 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basquetbol', '0025_remove_equipo_fundacion_remove_equipo_usuario'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='posicion',
            unique_together={('equipo', 'campeonato')},
        ),
    ]
