# Generated by Django 5.1.1 on 2024-11-20 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basquetbol', '0026_alter_posicion_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='posicion',
            unique_together=set(),
        ),
    ]
