# Generated by Django 5.1.1 on 2024-11-20 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basquetbol', '0027_alter_posicion_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='posicion',
            unique_together={('equipo', 'campeonato')},
        ),
    ]
