# Generated by Django 5.1.1 on 2024-11-20 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basquetbol', '0028_alter_posicion_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuartos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('goles_local', models.PositiveIntegerField(blank=True, null=True)),
                ('goles_visitante', models.PositiveIntegerField(blank=True, null=True)),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basquetbol.campeonato')),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuartos_local', to='basquetbol.equipo')),
                ('equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuartos_visitante', to='basquetbol.equipo')),
                ('estadio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basquetbol.estadio')),
            ],
        ),
    ]
