# Generated by Django 5.1.1 on 2024-11-21 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basquetbol', '0030_equipo_campeon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='campeonato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='basquetbol.campeonato'),
        ),
        migrations.CreateModel(
            name='Campeon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('campeonato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='campeon', to='basquetbol.campeonato')),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campeonados', to='basquetbol.equipo')),
            ],
        ),
    ]
