# Generated by Django 3.2 on 2024-12-06 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basquetbol', '0033_post_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='publicaciones_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='reply',
            name='author',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='post',
        ),
        migrations.RenameField(
            model_name='partidoestadistica',
            old_name='rebotes_equipo_local',
            new_name='rebotes_defensivos_equipo_local',
        ),
        migrations.RenameField(
            model_name='partidoestadistica',
            old_name='rebotes_equipo_visitante',
            new_name='rebotes_defensivos_equipo_visitante',
        ),
        migrations.AddField(
            model_name='partidoestadistica',
            name='rebotes_ofensivos_equipo_local',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partidoestadistica',
            name='rebotes_ofensivos_equipo_visitante',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partidoestadistica',
            name='robos_equipo_local',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partidoestadistica',
            name='robos_equipo_visitante',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
        migrations.AddField(
            model_name='comentario',
            name='publicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='basquetbol.publicacion'),
        ),
    ]
